name: python-course-for-gis-pros
channels:
  - conda-forge
  - pkerichang
dependencies:
  - python
  - numpy
  - libgdal
  - rtree
  - pip:
    - sphinx-gallery
    - pandas
    - matplotlib
    - gdal
    - fiona
    - shapely
    - rasterio==1.0a12
    - geopandas
    - geojson
    
