name: example-environment
channels:
  - conda-forge
  - pkerichang
dependencies:
  - python
  - numpy
  - libgdal
  - spatialindex
  - rtree
  - pip:
    - sphinx-gallery
    - pandas
    - matplotlib
    - gdal
    - fiona
    - shapely
    - rasterio
    - geopandas
    - geojson
